/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ChatGenerationEnqueue": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ChatGenerationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ChatGenerationStartToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ChatGenerationWorkflow": {
      "name": string
      "qualifier": string
      "type": "sst.aws.Workflow"
    }
    "GmailLiveSyncApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "GmailLiveSyncConnections": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GmailLiveSyncTokenSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GmailLiveSyncWebSocketHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MailBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MailIngestToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MailIngress": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MailReceiptTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
  }
}

import "sst"
export {}