/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "MailBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MailIngestToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MailIngress": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MailOutbound": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MailReceiptTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "MailSendToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}