/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitePasswordRouteImport } from './routes/site-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiSitePasswordRouteImport } from './routes/api/site-password'
import { Route as ApiPreviewPersonaRouteImport } from './routes/api/preview-persona'
import { Route as ApiOpenapiRouteImport } from './routes/api/openapi'
import { Route as ApiV1SendRouteImport } from './routes/api/v1/send'
import { Route as ApiOrpcSplatRouteImport } from './routes/api/orpc.$'
import { Route as ApiGmailCallbackRouteImport } from './routes/api/gmail.callback'
import { Route as ApiConnectorsCallbackRouteImport } from './routes/api/connectors.callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiInternalGmailCredentialsRotateRouteImport } from './routes/api.internal.gmail-credentials.rotate'
import { Route as ApiChatRunsRunIdStreamRouteImport } from './routes/api/chat.runs.$runId.stream'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitePasswordRoute = SitePasswordRouteImport.update({
  id: '/site-password',
  path: '/site-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitePasswordRoute = ApiSitePasswordRouteImport.update({
  id: '/api/site-password',
  path: '/api/site-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewPersonaRoute = ApiPreviewPersonaRouteImport.update({
  id: '/api/preview-persona',
  path: '/api/preview-persona',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiRoute = ApiOpenapiRouteImport.update({
  id: '/api/openapi',
  path: '/api/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SendRoute = ApiV1SendRouteImport.update({
  id: '/api/v1/send',
  path: '/api/v1/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailCallbackRoute = ApiGmailCallbackRouteImport.update({
  id: '/api/gmail/callback',
  path: '/api/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectorsCallbackRoute = ApiConnectorsCallbackRouteImport.update({
  id: '/api/connectors/callback',
  path: '/api/connectors/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalGmailCredentialsRotateRoute =
  ApiInternalGmailCredentialsRotateRouteImport.update({
    id: '/api/internal/gmail-credentials/rotate',
    path: '/api/internal/gmail-credentials/rotate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRunsRunIdStreamRoute = ApiChatRunsRunIdStreamRouteImport.update({
  id: '/api/chat/runs/$runId/stream',
  path: '/api/chat/runs/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/home': typeof HomeRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/site-password': typeof SitePasswordRoute
  '/terms': typeof TermsRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/api/preview-persona': typeof ApiPreviewPersonaRoute
  '/api/site-password': typeof ApiSitePasswordRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connectors/callback': typeof ApiConnectorsCallbackRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/v1/send': typeof ApiV1SendRoute
  '/api/internal/gmail-credentials/rotate': typeof ApiInternalGmailCredentialsRotateRoute
  '/api/chat/runs/$runId/stream': typeof ApiChatRunsRunIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/home': typeof HomeRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/site-password': typeof SitePasswordRoute
  '/terms': typeof TermsRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/api/preview-persona': typeof ApiPreviewPersonaRoute
  '/api/site-password': typeof ApiSitePasswordRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connectors/callback': typeof ApiConnectorsCallbackRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/v1/send': typeof ApiV1SendRoute
  '/api/internal/gmail-credentials/rotate': typeof ApiInternalGmailCredentialsRotateRoute
  '/api/chat/runs/$runId/stream': typeof ApiChatRunsRunIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/home': typeof HomeRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/site-password': typeof SitePasswordRoute
  '/terms': typeof TermsRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/api/preview-persona': typeof ApiPreviewPersonaRoute
  '/api/site-password': typeof ApiSitePasswordRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connectors/callback': typeof ApiConnectorsCallbackRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/v1/send': typeof ApiV1SendRoute
  '/api/internal/gmail-credentials/rotate': typeof ApiInternalGmailCredentialsRotateRoute
  '/api/chat/runs/$runId/stream': typeof ApiChatRunsRunIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/home'
    | '/imprint'
    | '/privacy'
    | '/settings'
    | '/site-password'
    | '/terms'
    | '/api/openapi'
    | '/api/preview-persona'
    | '/api/site-password'
    | '/api/waitlist'
    | '/api/auth/$'
    | '/api/connectors/callback'
    | '/api/gmail/callback'
    | '/api/orpc/$'
    | '/api/v1/send'
    | '/api/internal/gmail-credentials/rotate'
    | '/api/chat/runs/$runId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/home'
    | '/imprint'
    | '/privacy'
    | '/settings'
    | '/site-password'
    | '/terms'
    | '/api/openapi'
    | '/api/preview-persona'
    | '/api/site-password'
    | '/api/waitlist'
    | '/api/auth/$'
    | '/api/connectors/callback'
    | '/api/gmail/callback'
    | '/api/orpc/$'
    | '/api/v1/send'
    | '/api/internal/gmail-credentials/rotate'
    | '/api/chat/runs/$runId/stream'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cookies'
    | '/home'
    | '/imprint'
    | '/privacy'
    | '/settings'
    | '/site-password'
    | '/terms'
    | '/api/openapi'
    | '/api/preview-persona'
    | '/api/site-password'
    | '/api/waitlist'
    | '/api/auth/$'
    | '/api/connectors/callback'
    | '/api/gmail/callback'
    | '/api/orpc/$'
    | '/api/v1/send'
    | '/api/internal/gmail-credentials/rotate'
    | '/api/chat/runs/$runId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  HomeRoute: typeof HomeRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SitePasswordRoute: typeof SitePasswordRoute
  TermsRoute: typeof TermsRoute
  ApiOpenapiRoute: typeof ApiOpenapiRoute
  ApiPreviewPersonaRoute: typeof ApiPreviewPersonaRoute
  ApiSitePasswordRoute: typeof ApiSitePasswordRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConnectorsCallbackRoute: typeof ApiConnectorsCallbackRoute
  ApiGmailCallbackRoute: typeof ApiGmailCallbackRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
  ApiV1SendRoute: typeof ApiV1SendRoute
  ApiInternalGmailCredentialsRotateRoute: typeof ApiInternalGmailCredentialsRotateRoute
  ApiChatRunsRunIdStreamRoute: typeof ApiChatRunsRunIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-password': {
      id: '/site-password'
      path: '/site-password'
      fullPath: '/site-password'
      preLoaderRoute: typeof SitePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-password': {
      id: '/api/site-password'
      path: '/api/site-password'
      fullPath: '/api/site-password'
      preLoaderRoute: typeof ApiSitePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview-persona': {
      id: '/api/preview-persona'
      path: '/api/preview-persona'
      fullPath: '/api/preview-persona'
      preLoaderRoute: typeof ApiPreviewPersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi': {
      id: '/api/openapi'
      path: '/api/openapi'
      fullPath: '/api/openapi'
      preLoaderRoute: typeof ApiOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/send': {
      id: '/api/v1/send'
      path: '/api/v1/send'
      fullPath: '/api/v1/send'
      preLoaderRoute: typeof ApiV1SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/callback': {
      id: '/api/gmail/callback'
      path: '/api/gmail/callback'
      fullPath: '/api/gmail/callback'
      preLoaderRoute: typeof ApiGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/callback': {
      id: '/api/connectors/callback'
      path: '/api/connectors/callback'
      fullPath: '/api/connectors/callback'
      preLoaderRoute: typeof ApiConnectorsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/gmail-credentials/rotate': {
      id: '/api/internal/gmail-credentials/rotate'
      path: '/api/internal/gmail-credentials/rotate'
      fullPath: '/api/internal/gmail-credentials/rotate'
      preLoaderRoute: typeof ApiInternalGmailCredentialsRotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/runs/$runId/stream': {
      id: '/api/chat/runs/$runId/stream'
      path: '/api/chat/runs/$runId/stream'
      fullPath: '/api/chat/runs/$runId/stream'
      preLoaderRoute: typeof ApiChatRunsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  HomeRoute: HomeRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SitePasswordRoute: SitePasswordRoute,
  TermsRoute: TermsRoute,
  ApiOpenapiRoute: ApiOpenapiRoute,
  ApiPreviewPersonaRoute: ApiPreviewPersonaRoute,
  ApiSitePasswordRoute: ApiSitePasswordRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConnectorsCallbackRoute: ApiConnectorsCallbackRoute,
  ApiGmailCallbackRoute: ApiGmailCallbackRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
  ApiV1SendRoute: ApiV1SendRoute,
  ApiInternalGmailCredentialsRotateRoute:
    ApiInternalGmailCredentialsRotateRoute,
  ApiChatRunsRunIdStreamRoute: ApiChatRunsRunIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
