/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitePasswordRouteImport } from './routes/site-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GoogleScopeRepairRouteImport } from './routes/google-scope-repair'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSitePasswordRouteImport } from './routes/api/site-password'
import { Route as ApiOrpcSplatRouteImport } from './routes/api/orpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const SitePasswordRoute = SitePasswordRouteImport.update({
  id: '/site-password',
  path: '/site-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleScopeRepairRoute = GoogleScopeRepairRouteImport.update({
  id: '/google-scope-repair',
  path: '/google-scope-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitePasswordRoute = ApiSitePasswordRouteImport.update({
  id: '/api/site-password',
  path: '/api/site-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/google-scope-repair': typeof GoogleScopeRepairRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site-password': typeof SitePasswordRoute
  '/api/site-password': typeof ApiSitePasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/google-scope-repair': typeof GoogleScopeRepairRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site-password': typeof SitePasswordRoute
  '/api/site-password': typeof ApiSitePasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/google-scope-repair': typeof GoogleScopeRepairRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site-password': typeof SitePasswordRoute
  '/api/site-password': typeof ApiSitePasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/google-scope-repair'
    | '/home'
    | '/login'
    | '/settings'
    | '/signup'
    | '/site-password'
    | '/api/site-password'
    | '/api/auth/$'
    | '/api/orpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/google-scope-repair'
    | '/home'
    | '/login'
    | '/settings'
    | '/signup'
    | '/site-password'
    | '/api/site-password'
    | '/api/auth/$'
    | '/api/orpc/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/google-scope-repair'
    | '/home'
    | '/login'
    | '/settings'
    | '/signup'
    | '/site-password'
    | '/api/site-password'
    | '/api/auth/$'
    | '/api/orpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GoogleScopeRepairRoute: typeof GoogleScopeRepairRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitePasswordRoute: typeof SitePasswordRoute
  ApiSitePasswordRoute: typeof ApiSitePasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site-password': {
      id: '/site-password'
      path: '/site-password'
      fullPath: '/site-password'
      preLoaderRoute: typeof SitePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-scope-repair': {
      id: '/google-scope-repair'
      path: '/google-scope-repair'
      fullPath: '/google-scope-repair'
      preLoaderRoute: typeof GoogleScopeRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-password': {
      id: '/api/site-password'
      path: '/api/site-password'
      fullPath: '/api/site-password'
      preLoaderRoute: typeof ApiSitePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GoogleScopeRepairRoute: GoogleScopeRepairRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitePasswordRoute: SitePasswordRoute,
  ApiSitePasswordRoute: ApiSitePasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
