export const githubSstSecrets = {
  APP_SITE_PASSWORD: "AppSitePassword",
  BETTER_AUTH_SECRET: "BetterAuthSecret",
  CHAT_GENERATION_START_TOKEN: "ChatGenerationStartToken",
  CONNECTOR_TOKEN_ENCRYPTION_KEY: "ConnectorTokenEncryptionKey",
  DATABASE_URL: "DatabaseUrl",
  GMAIL_CREDENTIAL_ROTATION_TOKEN: "GmailCredentialRotationToken",
  GMAIL_LIVE_SYNC_TOKEN_SECRET: "GmailLiveSyncTokenSecret",
  GMAIL_PUBSUB_PROCESS_TOKEN: "GmailPubSubProcessToken",
  GMAIL_TOKEN_ENCRYPTION_KEY: "GmailTokenEncryptionKey",
  GMAIL_TOKEN_ENCRYPTION_KEY_CURRENT: "GmailTokenEncryptionKeyCurrent",
  GOOGLE_AUTH_CLIENT_ID: "GoogleAuthClientId",
  GOOGLE_AUTH_CLIENT_SECRET: "GoogleAuthClientSecret",
  GOOGLE_CALENDAR_CLIENT_ID: "GoogleCalendarClientId",
  GOOGLE_CALENDAR_CLIENT_SECRET: "GoogleCalendarClientSecret",
  GOOGLE_GMAIL_CLIENT_ID: "GoogleGmailClientId",
  GOOGLE_GMAIL_CLIENT_SECRET: "GoogleGmailClientSecret",
  LINEAR_CLIENT_ID: "LinearClientId",
  LINEAR_CLIENT_SECRET: "LinearClientSecret",
  MAIL_INGEST_TOKEN: "MailIngestToken",
  OPENROUTER_API_KEY: "OpenrouterApiKey",
  POLAR_ACCESS_TOKEN: "PolarAccessToken",
  POLAR_WEBHOOK_SECRET: "PolarWebhookSecret",
  QUIETER_MAIL_API_KEY: "QuieterMailApiKey",
  R2_ACCESS_KEY_ID: "R2AccessKeyId",
  R2_SECRET_ACCESS_KEY: "R2SecretAccessKey",
  SENTRY_DSN: "SentryDsn",
} as const;

export type GithubSstSecretName = keyof typeof githubSstSecrets;
