export { assertDatabaseConfigured, db, type DatabaseClient } from "./client";
export {
  account,
  apikey,
  authRelations,
  chat,
  chatMessage,
  invitation,
  mailbox,
  mailDomain,
  member,
  organization,
  passkey,
  session,
  tables,
  user,
  verification,
  waitlistSignup,
  type ChatMessagePart,
  type ChatMessageRole,
  type MailDomainCheckResult,
  type MailDomainDnsRecord,
  type MailDomainStatus,
  type MailboxSwitcherOrder,
} from "./schema";
